import type { Locale } from "@/i18n/config";

type CopyDictionary = Record<string, string>;

const fr: CopyDictionary = {
  "Reading your website": "Lecture de votre site web",
  "Services, products, sectors, careers and customer pages": "Offres, produits, secteurs, recrutements et références clients",
  "Mapping how your company works": "Analyse de votre activité",
  "Offerings, value chain, hiring signals and regulation": "Offres, chaîne de valeur, recrutements et réglementation",
  "Matching 570 real use cases": "Recherche parmi 570 cas d’usage réels",
  "One search per high-potential process": "Un rapprochement pour chaque processus prioritaire",
  "Designing your three agents": "Conception de vos trois agents",
  "Workflows, integrations, controls and time saved": "Workflows, intégrations, contrôles et temps estimé",
  "Free": "Gratuit",
  "No sign-up": "Sans inscription",
  "Anonymous": "Anonyme",
  "About a minute": "Environ une minute",
  "Pages": "Pages",
  "Offer": "Offre",
  "Scale": "Taille",
  "Process": "Processus",
  "Hiring": "Recrutement",
  "Rules": "Réglementation",
  "Match": "Correspondance",
  "{count} comparable use cases matched": "{count} cas d’usage comparables identifiés",
  "Agent foundry": "Atelier d’agents IA",
  "Blueprint ready": "Votre plan est prêt",
  "Your agent team is ready": "Vos pistes d’agents sont prêtes",
  "Your agent team will appear here": "Vos pistes apparaîtront ici",
  "saved / week": "économisées / semaine",
  "Website": "Site web",
  "Operations": "Activité",
  "Benchmark": "Références",
  "Agents": "Agents",
  "What we are finding": "Ce que nous repérons",
  "Copilot": "Copilote",
  "Human in the loop": "Avec validation humaine",
  "Fully autonomous": "Autonome",
  "Works side by side with your team": "Travaille aux côtés de vos équipes",
  "Acts, then asks for approval": "Agit, puis demande validation",
  "Runs scheduled, controlled workflows": "Suit des workflows planifiés et contrôlés",
  "Private": "Privé",
  "Tap an agent for its workflow and integrations": "Sélectionnez un agent pour voir son workflow et ses intégrations",
  "Full blueprint": "Voir le plan complet",
  "Built from your own website, not a template": "Conçu à partir de votre site, pas d’un modèle",
  "Built from your own pages, not a template": "Conçu à partir de vos pages, pas d’un modèle",
  "Copy the setup (model ": "Copier la configuration (modèle ",
  "Copied, paste it in WonkaChat": "Copié. Collez-le dans WonkaChat",
  "Copy WonkaChat setup": "Copier la configuration WonkaChat",
  "Low effort": "Effort faible",
  "Medium effort": "Effort moyen",
  "High effort": "Effort élevé",
  "Low": "Faible",
  "Medium": "Moyen",
  "High": "Élevé",
  "saved every week": "économisées chaque semaine",
  "How it runs": "Fonctionnement",
  "Trigger": "Déclencheur",
  "Human check": "Validation humaine",
  "What we saw": "Ce que nous avons observé",
  "Plugs into": "Intégrations",
  "Watch it run": "Voir l’agent en action",
  "An illustrative run, built from your blueprint. Figures are demo data.": "Une exécution type, construite à partir de votre plan. Les chiffres sont des données de démonstration.",
  "Demo data": "Données de démonstration",
  "New event": "Nouvel événement",
  "Running": "En cours",
  "Done": "Terminé",
  "Use this draft": "Utiliser ce brouillon",
  "Draft inserted": "Brouillon inséré",
  "Approve": "Valider",
  "Approved": "Validé",
  "Run on schedule": "Planifier",
  "Scheduled": "Planifié",
  "estimated hours saved every week": "heures estimées gagnées chaque semaine",
  "Built and run in WonkaChat": "Conçu et exécuté dans WonkaChat",
  "Outcome": "Résultat attendu",
  "Scope this agent": "Cadrer cet agent",
  "returned to the team every week": "récupérées par l’équipe chaque semaine",
  "working days freed up every month": "jours ouvrés libérés par mois",
  "agents, from copilot to autonomous": "agents, du copilote à l’autonome",
  "Your blueprint is ready": "Votre plan d’agents est prêt",
  "What shaped your blueprint": "Les éléments pris en compte",
  "Choose an agent to explore": "Choisissez un agent à explorer",
  "Compare the workflow, integrations and weekly time saved.": "Comparez le workflow, les intégrations et le temps estimé.",
  "Start here": "Commencez ici",
  "Viewing now": "Sélectionné",
  "View details": "Voir le détail",
  "Next step": "Pour aller plus loin",
  "Turn this blueprint into your first live agent.": "Passez de ce plan à votre premier agent en production.",
  "30-minute call with a Wonka AI engineer": "Un échange de 30 minutes avec un ingénieur Wonka AI",
  "Validate volumes, integrations and ROI": "Valider les volumes, les intégrations et le retour attendu",
  "Leave with a scoped delivery plan": "Repartir avec un plan de déploiement cadré",
  "Use my agents now": "Utiliser mes agents",
  "Import my 3 agents into WonkaChat": "Importer mes 3 agents dans WonkaChat",
  "Book a 30 min call": "Réserver un échange de 30 min",
  "Backed by Nvidia Inception and Microsoft for Startups.": "Soutenu par Nvidia Inception et Microsoft for Startups.",
  "Time savings are directional estimates based on recurring tasks in the benchmark. Validate them against real volumes before investment.": "Les gains de temps sont des estimations indicatives fondées sur des tâches récurrentes. Vérifiez-les à partir de vos volumes avant d’investir.",
  "Try another company": "Analyser une autre entreprise",
  "identified for your team": "identifiées pour votre équipe",
  "Free AI agent blueprint": "Plan gratuit d’agents IA",
  " · ready in about a minute": " · prêt en une minute environ",
  "Use my agents": "Utiliser mes agents",
  "Get mine": "Obtenir mon plan",
  "Please complete the verification check.": "Veuillez terminer la vérification.",
  "Site not readable · using public web research": "Site inaccessible · recherche dans les sources publiques",
  "Too many requests. Please try again later.": "Trop de demandes. Réessayez dans quelques minutes.",
  "We could not build the blueprint right now. Please try again.": "Impossible de créer le plan pour le moment. Réessayez.",
  "See the 3 AI agents your company should build first.": "Découvrez les trois agents IA à envisager en priorité.",
  "Enter your website. We map how your company works and design three agents around your own processes.": "Saisissez votre site. Nous analysons votre activité et proposons trois agents liés à vos processus.",
  "Enter your website. We read your pages, map how your company actually works, match it against 570 real enterprise AI projects and design three agents built around your own processes, with the hours each one gives back every week.": "Saisissez votre site. Nous analysons vos pages, comparons vos processus à 570 projets d’IA en entreprise et proposons trois agents avec une estimation du temps qu’ils pourraient libérer.",
  "Company website": "Site web de l’entreprise",
  "Building agents…": "Création des agents…",
  "Build my agent team": "Créer mon plan d’agents",
  "Verification failed. Please try again.": "La vérification a échoué. Réessayez.",
  "No company or client name appears in the blueprint. Public web research only. By continuing, you agree to our ": "Le plan ne mentionne ni le nom de votre entreprise ni celui de ses clients. L’analyse porte sur des informations publiques. En continuant, vous acceptez notre ",
  "privacy policy": "politique de confidentialité",
  "Your team is too good for repetitive work.": "Votre équipe mérite mieux que les tâches répétitives.",
  "Find out which three agents would take it off their plate. Free, ready in about a minute.": "Découvrez trois agents qui pourraient prendre en charge ces tâches. C’est gratuit et prêt en une minute environ.",
  "Prefer to talk first? ": "Vous préférez en parler d’abord ? ",
  "What you get": "Ce que vous obtenez",
  "A consultant-grade AI plan. Free, in a minute.": "Un plan d’agents IA conçu pour votre activité. Gratuit, en une minute.",
  "The same use-case prioritisation we run with clients in our Start AI programs, as a first version. Enter a website and it is yours.": "Une première priorisation des cas d’usage, inspirée de notre accompagnement Start AI. Saisissez un site pour obtenir votre plan.",
  "Build my blueprint": "Créer mon plan",
  "Your AI agent blueprint": "Votre plan d’agents IA",
  "Included": "Inclus",
  "Your company, mapped": "Votre activité analysée",
  "Offerings, value chain and the processes where work repeats": "Offres, chaîne de valeur et processus récurrents",
  "Benchmark against 570 AI projects": "Comparaison avec 570 projets d’IA",
  "Each process matched to patterns that already work": "Chaque processus rapproché de cas d’usage éprouvés",
  "Three agents, designed for you": "Trois agents adaptés à votre activité",
  "A copilot, a human-in-the-loop and an autonomous agent": "Un copilote, un agent avec validation humaine et un agent autonome",
  "Workflow for every agent": "Le workflow de chaque agent",
  "Trigger, steps and where a human stays in control": "Déclencheur, étapes et points de validation humaine",
  "The tools each agent plugs into": "Les outils utilisés par chaque agent",
  "Outlook, SharePoint, Teams, Odoo, Salesforce and more": "Outlook, SharePoint, Teams, Odoo, Salesforce et d’autres",
  "Hours saved and build effort": "Temps estimé et effort de réalisation",
  "So you know which agent to build first": "Pour identifier l’agent à étudier en premier",
  "No call. No sign-up. No credit card.": "Sans appel, sans inscription et sans carte bancaire.",
  "Copy any agent straight into WonkaChat.": "Copiez la configuration d’un agent dans WonkaChat.",
  "Your blueprint": "Votre plan",
  "Agents that move work forward": "Des agents qui font avancer le travail",
  "Each agent in your blueprint becomes a WonkaChat agent that picks up the task, runs the steps and hands back the result.": "Chaque agent de votre plan peut devenir un agent WonkaChat qui prend en charge une tâche, suit les étapes prévues et vous remet le résultat.",
  "Plugged into your tools": "Connectés à vos outils",
  "WonkaChat board where AI agents move tasks from to do to done": "Tableau WonkaChat où les agents IA font avancer les tâches jusqu’à leur validation",
  "Tools WonkaChat connects to, including Outlook, SharePoint, Odoo and Salesforce": "Outils connectés à WonkaChat, dont Outlook, SharePoint, Odoo et Salesforce",
  "Outlook, SharePoint, Teams, Odoo, Salesforce, Notion and more, so agents work where your data already lives.": "Outlook, SharePoint, Teams, Odoo, Salesforce, Notion et d’autres : vos agents travaillent là où se trouvent déjà vos données.",
  "After the blueprint": "Après le plan",
  "Your blueprint doesn't\nstay a slide.": "Votre plan ne reste pas\nsur une diapositive.",
  "Turn the agents you like into working agents in WonkaChat, the AI workspace Itzu rolled out to every employee.": "Transformez les agents que vous retenez en agents opérationnels dans WonkaChat, l’espace de travail IA déployé chez Itzu pour ses équipes.",
  "Start with WonkaChat": "Découvrir WonkaChat",
  "Or book a 30 min call": "Ou réserver un échange de 30 min",
  "How it works": "Comment ça marche",
  "From website to agent team\nin three steps.": "Du site de votre entreprise\nà trois agents, en trois étapes.",
  "We read your website": "Nous analysons votre site",
  "Services, products, sectors, careers and customer pages, plus public sources like job posts and news. We map what you sell, how work flows and where it repeats.": "Offres, produits, secteurs, recrutements et références clients, ainsi que des sources publiques. Nous repérons vos activités, vos workflows et les tâches récurrentes.",
  "We match 570 real use cases": "Nous comparons 570 cas d’usage",
  "Each high-potential process is matched separately against an anonymised benchmark of enterprise AI projects, so every agent builds on a pattern that already works.": "Chaque processus prioritaire est rapproché séparément d’un benchmark anonymisé de projets d’IA en entreprise. Les agents s’appuient ainsi sur des cas d’usage déjà observés.",
  "Get three agents, then build one": "Choisissez un agent à déployer",
  "Pick the agent with the best return. A Wonka engineer validates the scope with you and ships it in weeks.": "Identifiez l’agent au meilleur potentiel. Un ingénieur Wonka peut ensuite valider le périmètre avec vous et préparer son déploiement.",
  "Your data is always yours.": "Vos données restent les vôtres.",
  "Is the blueprint really free?": "Le plan est-il vraiment gratuit ?",
  "Yes. No sign-up, no email and no credit card. Enter a website and you get the full blueprint on screen.": "Oui. Sans inscription, sans email et sans carte bancaire. Saisissez un site pour afficher le plan complet.",
  "What information do you use about my company?": "Quelles informations utilisez-vous sur mon entreprise ?",
  "Only public web information about the domain you enter. We never ask for internal documents, and the result never shows your company name or any benchmark client name.": "Uniquement les informations publiques associées au domaine saisi. Nous ne demandons aucun document interne et le résultat ne révèle ni le nom de votre entreprise ni celui d’un client du benchmark.",
  "Where do the 570 use cases come from?": "D’où viennent les 570 cas d’usage ?",
  "From an anonymised benchmark of enterprise AI projects. Client names and mission details are removed before any pattern is used.": "D’un benchmark anonymisé de projets d’IA en entreprise. Les noms des clients et les détails des missions sont retirés avant toute utilisation.",
  "How reliable are the time-saving estimates?": "Quelle est la fiabilité des estimations de temps gagné ?",
  "They are directional, based on recurring tasks in comparable projects. On a scoping call we validate them against your real volumes before anything is built.": "Elles sont indicatives et s’appuient sur des tâches récurrentes observées dans des projets comparables. Nous les vérifions avec vos volumes réels avant tout développement.",
  "Which tools can the agents connect to?": "À quels outils les agents peuvent-ils se connecter ?",
  "Microsoft 365 (Outlook, SharePoint, Teams), Odoo, SAP, Dynamics, Salesforce, HubSpot, Jira and more. Every blueprint lists the integrations each agent needs.": "Microsoft 365 (Outlook, SharePoint, Teams), Odoo, SAP, Dynamics, Salesforce, HubSpot, Jira et d’autres. Le plan précise les intégrations requises pour chaque agent.",
  "What happens after I get my blueprint?": "Que se passe-t-il après la création du plan ?",
  "Nothing, unless you want it to. If an agent looks worth building, book a 30-minute call and a Wonka engineer turns it into a scoped delivery plan.": "Rien, sauf si vous le souhaitez. Si un agent mérite d’être développé, réservez un échange de 30 minutes pour cadrer son déploiement avec un ingénieur Wonka.",
  "Questions before you try it": "Vos questions avant de commencer",
  "FAQ": "Questions fréquentes",
  "Backed by": "Soutenu par",
  "Scaled AI agents across their network.": "Des agents IA déployés dans leur réseau.",
  "Got fast-tracked to AI-native.": "Une transition accélérée vers l’IA.",
  "Deployed AI for all of their employees in weeks.": "L’IA déployée auprès de leurs équipes en quelques semaines.",
  "Customer proof": "Ils nous font confiance",
  "50% time reduction on support emails across +70 employees at N-allo (Engie)": "50 % de temps gagné sur le traitement des emails support chez N-allo (Engie), pour plus de 70 personnes",
  "Every Itzu employee has access to their personal WonkaChat that saves them multiple hours each week.": "Chaque personne chez Itzu dispose de son espace WonkaChat et gagne plusieurs heures par semaine.",
  "With Wonka, your usual working day is finished at 3 pm.": "Avec Wonka, votre journée de travail habituelle se termine à 15 h.",
};

const nl: CopyDictionary = {
  "Reading your website": "Je website lezen",
  "Services, products, sectors, careers and customer pages": "Diensten, producten, sectoren, vacatures en klantpagina’s",
  "Mapping how your company works": "Je bedrijfswerking in kaart brengen",
  "Offerings, value chain, hiring signals and regulation": "Aanbod, waardeketen, vacatures en regelgeving",
  "Matching 570 real use cases": "570 echte usecases vergelijken",
  "One search per high-potential process": "Een vergelijking per kansrijk proces",
  "Designing your three agents": "Je drie agents ontwerpen",
  "Workflows, integrations, controls and time saved": "Workflows, koppelingen, controles en tijdswinst",
  "Free": "Gratis",
  "No sign-up": "Geen registratie",
  "Anonymous": "Anoniem",
  "About a minute": "Ongeveer een minuut",
  "Pages": "Pagina’s",
  "Offer": "Aanbod",
  "Scale": "Omvang",
  "Process": "Proces",
  "Hiring": "Vacatures",
  "Rules": "Regelgeving",
  "Match": "Match",
  "{count} comparable use cases matched": "{count} vergelijkbare use cases gevonden",
  "Agent foundry": "Agentenatelier",
  "Blueprint ready": "Je plan is klaar",
  "Your agent team is ready": "Je agentvoorstellen zijn klaar",
  "Your agent team will appear here": "Je voorstellen verschijnen hier",
  "saved / week": "bespaard / week",
  "Website": "Website",
  "Operations": "Bedrijfswerking",
  "Benchmark": "Referenties",
  "Agents": "Agents",
  "What we are finding": "Wat we ontdekken",
  "Copilot": "Copiloot",
  "Human in the loop": "Met menselijke controle",
  "Fully autonomous": "Autonoom",
  "Works side by side with your team": "Werkt samen met je team",
  "Acts, then asks for approval": "Voert uit en vraagt daarna goedkeuring",
  "Runs scheduled, controlled workflows": "Voert geplande, gecontroleerde workflows uit",
  "Private": "Privé",
  "Tap an agent for its workflow and integrations": "Selecteer een agent voor de workflow en koppelingen",
  "Full blueprint": "Volledig plan bekijken",
  "Built from your own website, not a template": "Gebaseerd op je website, niet op een sjabloon",
  "Built from your own pages, not a template": "Gebaseerd op je pagina’s, niet op een sjabloon",
  "Copied, paste it in WonkaChat": "Gekopieerd. Plak het in WonkaChat",
  "Copy WonkaChat setup": "WonkaChat-configuratie kopiëren",
  "Low effort": "Lage inspanning",
  "Medium effort": "Gemiddelde inspanning",
  "High effort": "Hoge inspanning",
  "Low": "Laag",
  "Medium": "Gemiddeld",
  "High": "Hoog",
  "saved every week": "elke week bespaard",
  "How it runs": "Werking",
  "Trigger": "Trigger",
  "Human check": "Menselijke controle",
  "What we saw": "Wat we zagen",
  "Plugs into": "Koppelingen",
  "Watch it run": "Bekijk de agent aan het werk",
  "An illustrative run, built from your blueprint. Figures are demo data.": "Een voorbeeldrun, opgebouwd uit uw blueprint. De cijfers zijn demodata.",
  "Demo data": "Demodata",
  "New event": "Nieuwe gebeurtenis",
  "Running": "Bezig",
  "Done": "Klaar",
  "Use this draft": "Concept gebruiken",
  "Draft inserted": "Concept ingevoegd",
  "Approve": "Goedkeuren",
  "Approved": "Goedgekeurd",
  "Run on schedule": "Inplannen",
  "Scheduled": "Ingepland",
  "estimated hours saved every week": "geschatte uren bespaard per week",
  "Built and run in WonkaChat": "Gebouwd en uitgevoerd in WonkaChat",
  "Outcome": "Verwacht resultaat",
  "Scope this agent": "Deze agent afbakenen",
  "returned to the team every week": "elke week terug naar het team",
  "working days freed up every month": "werkdagen vrijgemaakt per maand",
  "agents, from copilot to autonomous": "agents, van copiloot tot autonoom",
  "Your blueprint is ready": "Je agentplan is klaar",
  "What shaped your blueprint": "Wat de voorstellen heeft bepaald",
  "Choose an agent to explore": "Kies een agent om te bekijken",
  "Compare the workflow, integrations and weekly time saved.": "Vergelijk de workflow, koppelingen en geschatte tijdswinst.",
  "Start here": "Begin hier",
  "Viewing now": "Geselecteerd",
  "View details": "Details bekijken",
  "Next step": "Volgende stap",
  "Turn this blueprint into your first live agent.": "Maak van dit plan je eerste agent in productie.",
  "30-minute call with a Wonka AI engineer": "Een gesprek van 30 minuten met een Wonka AI-engineer",
  "Validate volumes, integrations and ROI": "Volumes, koppelingen en verwachte ROI valideren",
  "Leave with a scoped delivery plan": "Vertrekken met een afgebakend implementatieplan",
  "Use my agents now": "Mijn agents gebruiken",
  "Import my 3 agents into WonkaChat": "Mijn 3 agents importeren in WonkaChat",
  "Book a 30 min call": "Een gesprek van 30 min boeken",
  "Backed by Nvidia Inception and Microsoft for Startups.": "Gesteund door Nvidia Inception en Microsoft for Startups.",
  "Time savings are directional estimates based on recurring tasks in the benchmark. Validate them against real volumes before investment.": "De tijdswinst is een indicatieve raming op basis van terugkerende taken. Toets ze aan je werkelijke volumes voor je investeert.",
  "Try another company": "Een ander bedrijf analyseren",
  "identified for your team": "in kaart gebracht voor je team",
  "Free AI agent blueprint": "Gratis AI-agentplan",
  " · ready in about a minute": " · klaar in ongeveer een minuut",
  "Use my agents": "Mijn agents gebruiken",
  "Get mine": "Mijn plan maken",
  "Please complete the verification check.": "Voltooi de verificatie.",
  "Site not readable · using public web research": "Website niet leesbaar · openbare bronnen worden gebruikt",
  "Too many requests. Please try again later.": "Te veel aanvragen. Probeer het later opnieuw.",
  "We could not build the blueprint right now. Please try again.": "Je plan kan nu niet worden gemaakt. Probeer het opnieuw.",
  "See the 3 AI agents your company should build first.": "Ontdek welke drie AI-agents je bedrijf eerst kan bouwen.",
  "Enter your website. We map how your company works and design three agents around your own processes.": "Vul je website in. We brengen je werking in kaart en stellen drie agents voor je processen voor.",
  "Enter your website. We read your pages, map how your company actually works, match it against 570 real enterprise AI projects and design three agents built around your own processes, with the hours each one gives back every week.": "Vul je website in. We analyseren je pagina’s, vergelijken je processen met 570 echte AI-projecten en stellen drie agents voor, met een raming van de wekelijkse tijdswinst.",
  "Company website": "Website van je bedrijf",
  "Building agents…": "Agents samenstellen…",
  "Build my agent team": "Mijn agentplan maken",
  "Verification failed. Please try again.": "De verificatie is mislukt. Probeer het opnieuw.",
  "No company or client name appears in the blueprint. Public web research only. By continuing, you agree to our ": "Je bedrijfsnaam en klantnamen verschijnen niet in het plan. We gebruiken alleen openbare informatie. Door verder te gaan, ga je akkoord met ons ",
  "privacy policy": "privacybeleid",
  "Your team is too good for repetitive work.": "Je team is te waardevol voor repetitief werk.",
  "Find out which three agents would take it off their plate. Free, ready in about a minute.": "Ontdek welke drie agents die taken kunnen overnemen. Gratis en klaar in ongeveer een minuut.",
  "Prefer to talk first? ": "Praat je liever eerst? ",
  "What you get": "Wat je krijgt",
  "A consultant-grade AI plan. Free, in a minute.": "Een doordacht AI-agentplan voor je bedrijf. Gratis, in één minuut.",
  "The same use-case prioritisation we run with clients in our Start AI programs, as a first version. Enter a website and it is yours.": "Een eerste prioritering van usecases, geïnspireerd op onze Start AI-trajecten. Vul een website in en ontvang je plan.",
  "Build my blueprint": "Mijn plan maken",
  "Your AI agent blueprint": "Je AI-agentplan",
  "Included": "Inbegrepen",
  "Your company, mapped": "Je bedrijfswerking in kaart",
  "Offerings, value chain and the processes where work repeats": "Aanbod, waardeketen en terugkerende processen",
  "Benchmark against 570 AI projects": "Vergelijking met 570 AI-projecten",
  "Each process matched to patterns that already work": "Elk kansrijk proces gekoppeld aan beproefde patronen",
  "Three agents, designed for you": "Drie agents voor jouw bedrijf",
  "A copilot, a human-in-the-loop and an autonomous agent": "Een copiloot, een agent met menselijke controle en een autonome agent",
  "Workflow for every agent": "De workflow van elke agent",
  "Trigger, steps and where a human stays in control": "Trigger, stappen en momenten voor menselijke controle",
  "The tools each agent plugs into": "De tools waarmee elke agent werkt",
  "Outlook, SharePoint, Teams, Odoo, Salesforce and more": "Outlook, SharePoint, Teams, Odoo, Salesforce en meer",
  "Hours saved and build effort": "Geschatte tijdswinst en bouwinspanning",
  "So you know which agent to build first": "Zo weet je welke agent je eerst kunt bouwen",
  "No call. No sign-up. No credit card.": "Geen gesprek, geen registratie, geen kredietkaart.",
  "Copy any agent straight into WonkaChat.": "Kopieer de configuratie rechtstreeks naar WonkaChat.",
  "Your blueprint": "Je agentplan",
  "Agents that move work forward": "Agents die werk vooruithelpen",
  "Each agent in your blueprint becomes a WonkaChat agent that picks up the task, runs the steps and hands back the result.": "Elke agent uit je plan kan een WonkaChat-agent worden die een taak oppakt, de stappen uitvoert en het resultaat teruggeeft.",
  "Plugged into your tools": "Gekoppeld aan je tools",
  "WonkaChat board where AI agents move tasks from to do to done": "WonkaChat-bord waarop AI-agents taken van ‘te doen’ naar ‘klaar’ verplaatsen",
  "Tools WonkaChat connects to, including Outlook, SharePoint, Odoo and Salesforce": "Tools die met WonkaChat verbinden, waaronder Outlook, SharePoint, Odoo en Salesforce",
  "Outlook, SharePoint, Teams, Odoo, Salesforce, Notion and more, so agents work where your data already lives.": "Outlook, SharePoint, Teams, Odoo, Salesforce, Notion en meer. Zo werken agents waar je data al staat.",
  "After the blueprint": "Na het plan",
  "Your blueprint doesn't\nstay a slide.": "Je plan blijft niet\nop een slide staan.",
  "Turn the agents you like into working agents in WonkaChat, the AI workspace Itzu rolled out to every employee.": "Zet de agents die je kiest om in werkende WonkaChat-agents, de AI-werkruimte die Itzu voor alle medewerkers heeft uitgerold.",
  "Start with WonkaChat": "Aan de slag met WonkaChat",
  "Or book a 30 min call": "Of boek een gesprek van 30 min",
  "How it works": "Zo werkt het",
  "From website to agent team\nin three steps.": "Van bedrijfswebsite naar agentplan\nin drie stappen.",
  "We read your website": "We analyseren je website",
  "Services, products, sectors, careers and customer pages, plus public sources like job posts and news. We map what you sell, how work flows and where it repeats.": "Diensten, producten, sectoren, vacatures en klantpagina’s, aangevuld met openbare bronnen. We brengen je aanbod, workflows en terugkerende taken in kaart.",
  "We match 570 real use cases": "We vergelijken 570 echte usecases",
  "Each high-potential process is matched separately against an anonymised benchmark of enterprise AI projects, so every agent builds on a pattern that already works.": "Elk kansrijk proces wordt apart vergeleken met een geanonimiseerde benchmark van AI-projecten. Elke agent bouwt voort op een patroon dat al werkt.",
  "Get three agents, then build one": "Kies een agent om te bouwen",
  "Pick the agent with the best return. A Wonka engineer validates the scope with you and ships it in weeks.": "Kies de agent met het beste verwachte rendement. Een Wonka-engineer kan daarna de scope met je valideren en de implementatie voorbereiden.",
  "Your data is always yours.": "Je data blijft altijd van jou.",
  "Is the blueprint really free?": "Is het plan echt gratis?",
  "Yes. No sign-up, no email and no credit card. Enter a website and you get the full blueprint on screen.": "Ja. Geen registratie, e-mailadres of kredietkaart nodig. Vul een website in en je volledige plan verschijnt meteen.",
  "What information do you use about my company?": "Welke informatie gebruiken jullie over mijn bedrijf?",
  "Only public web information about the domain you enter. We never ask for internal documents, and the result never shows your company name or any benchmark client name.": "Alleen openbare online informatie over het domein dat je invult. We vragen nooit om interne documenten. Je bedrijfsnaam en namen van benchmarkklanten verschijnen niet in het resultaat.",
  "Where do the 570 use cases come from?": "Waar komen de 570 usecases vandaan?",
  "From an anonymised benchmark of enterprise AI projects. Client names and mission details are removed before any pattern is used.": "Uit een geanonimiseerde benchmark van AI-projecten bij bedrijven. Klantnamen en projectdetails worden verwijderd voordat patronen worden gebruikt.",
  "How reliable are the time-saving estimates?": "Hoe betrouwbaar zijn de ramingen van tijdswinst?",
  "They are directional, based on recurring tasks in comparable projects. On a scoping call we validate them against your real volumes before anything is built.": "Het zijn indicatieve ramingen op basis van terugkerende taken in vergelijkbare projecten. We toetsen ze aan je werkelijke volumes voordat er iets wordt gebouwd.",
  "Which tools can the agents connect to?": "Met welke tools kunnen de agents verbinden?",
  "Microsoft 365 (Outlook, SharePoint, Teams), Odoo, SAP, Dynamics, Salesforce, HubSpot, Jira and more. Every blueprint lists the integrations each agent needs.": "Microsoft 365 (Outlook, SharePoint, Teams), Odoo, SAP, Dynamics, Salesforce, HubSpot, Jira en meer. Je plan vermeldt welke koppelingen elke agent nodig heeft.",
  "What happens after I get my blueprint?": "Wat gebeurt er nadat ik mijn plan krijg?",
  "Nothing, unless you want it to. If an agent looks worth building, book a 30-minute call and a Wonka engineer turns it into a scoped delivery plan.": "Niets, tenzij je dat wilt. Lijkt een agent de moeite waard? Boek een gesprek van 30 minuten om de implementatie met een Wonka-engineer af te bakenen.",
  "Questions before you try it": "Vragen voordat je begint",
  "FAQ": "Veelgestelde vragen",
  "Backed by": "Gesteund door",
  "Scaled AI agents across their network.": "AI-agents opgeschaald binnen hun netwerk.",
  "Got fast-tracked to AI-native.": "Versneld AI-native geworden.",
  "Deployed AI for all of their employees in weeks.": "AI binnen enkele weken uitgerold voor alle medewerkers.",
  "Customer proof": "Vertrouwd door teams",
  "50% time reduction on support emails across +70 employees at N-allo (Engie)": "50% minder tijd aan supportmails bij N-allo (Engie), voor meer dan 70 medewerkers",
  "Every Itzu employee has access to their personal WonkaChat that saves them multiple hours each week.": "Elke medewerker bij Itzu heeft een eigen WonkaChat en bespaart zo meerdere uren per week.",
  "With Wonka, your usual working day is finished at 3 pm.": "Met Wonka zit je gewone werkdag erop om 15.00 uur.",
};

export function blueprintText(locale: Locale, english: string): string {
  if (locale === "fr") return fr[english] ?? english;
  if (locale === "nl") return nl[english] ?? english;
  return english;
}

export function blueprintOutputLanguage(locale: Locale): string {
  if (locale === "fr") return "French as used in France";
  if (locale === "nl") return "Dutch as used in Belgium";
  return "English";
}
