// Logo catalog aligned with Wonka Chat production MCP configuration.
export const btpIntegrations = [
  {"name": "Outlook", "src": "/images/visual/outlook.svg"},
  {"name": "Excel", "src": "/images/solution/card-3/logos/excel.svg"},
  {"name": "Teams", "src": "/images/visual/teams.svg"},
  {"name": "SharePoint", "src": "/images/visual/sharepoint.svg"},
  {"name": "Odoo", "src": "/images/solution/card-3/logos/odoo.svg"},
  {"name": "Airtable", "src": "/images/mcp-integrations/airtable.svg"},
  {"name": "Asana", "src": "/images/mcp-integrations/asana.svg"},
  {"name": "Attio", "src": "/images/mcp-integrations/attio.svg"},
  {"name": "Basecamp", "src": "/images/mcp-integrations/basecamp.svg"},
  {"name": "Bitbucket", "src": "/images/mcp-integrations/bitbucket.svg"},
  {"name": "Box", "src": "/images/mcp-integrations/box.svg"},
  {"name": "Brevo", "src": "/images/mcp-integrations/brevo.jpg"},
  {"name": "Cal.com", "src": "/images/mcp-integrations/cal-com.png"},
  {"name": "Canva", "src": "/images/mcp-integrations/canva.png"},
  {"name": "ClickUp", "src": "/images/mcp-integrations/clickup.svg"},
  {"name": "Close", "src": "/images/mcp-integrations/close.svg"},
  {"name": "Confluence", "src": "/images/mcp-integrations/confluence.svg"},
  {"name": "Contentful", "src": "/images/mcp-integrations/contentful.svg"},
  {"name": "Dropbox", "src": "/images/mcp-integrations/dropbox.svg"},
  {"name": "Dynamics 365", "src": "/images/mcp-integrations/dynamics-365.png"},
  {"name": "Eventbrite", "src": "/images/mcp-integrations/eventbrite.svg"},
  {"name": "Fathom", "src": "/images/mcp-integrations/fathom.png"},
  {"name": "Figma", "src": "/images/mcp-integrations/figma.svg"},
  {"name": "GitHub", "src": "/images/mcp-integrations/github.svg"},
  {"name": "GitLab", "src": "/images/mcp-integrations/gitlab.png"},
  {"name": "Gmail", "src": "/images/mcp-integrations/gmail.svg"},
  {"name": "Google Ads", "src": "/images/mcp-integrations/google-ads.png"},
  {"name": "Google Analytics", "src": "/images/mcp-integrations/google-analytics.svg"},
  {"name": "Google Calendar", "src": "/images/mcp-integrations/google-calendar.png"},
  {"name": "Google Docs", "src": "/images/mcp-integrations/google-docs.jpg"},
  {"name": "Google Drive", "src": "/images/mcp-integrations/google-drive.png"},
  {"name": "Google Sheets", "src": "/images/mcp-integrations/google-sheets.png"},
  {"name": "Google Workspace", "src": "/images/mcp-integrations/google-super.png"},
  {"name": "Greenhouse", "src": "/images/mcp-integrations/greenhouse.svg"},
  {"name": "HubSpot", "src": "/images/mcp-integrations/hubspot.svg"},
  {"name": "Intercom", "src": "/images/mcp-integrations/intercom.png"},
  {"name": "Jira", "src": "/images/mcp-integrations/jira.svg"},
  {"name": "Klaviyo", "src": "/images/mcp-integrations/klaviyo.svg"},
  {"name": "Leexi", "src": "/images/mcp-integrations/leexi.png"},
  {"name": "Linear", "src": "/images/mcp-integrations/linear.svg"},
  {"name": "LinkedIn", "src": "/images/mcp-integrations/linkedin.svg"},
  {"name": "Meta Ads", "src": "/images/mcp-integrations/meta-ads.jpg"},
  {"name": "Miro", "src": "/images/mcp-integrations/miro.png"},
  {"name": "Mailchimp", "src": "/images/mcp-integrations/mailchimp.png"},
  {"name": "Power BI", "src": "/images/mcp-integrations/power-bi.svg"},
  {"name": "Microsoft To Do", "src": "/images/mcp-integrations/microsoft-to-do.png"},
  {"name": "Monday.com", "src": "/images/mcp-integrations/monday-com.png"},
  {"name": "Notion", "src": "/images/mcp-integrations/notion.svg"},
  {"name": "OneDrive", "src": "/images/mcp-integrations/onedrive.svg"},
  {"name": "OneNote", "src": "/images/mcp-integrations/onenote.png"},
  {"name": "Outlook Calendar", "src": "/images/mcp-integrations/outlook-calendar.jpg"},
  {"name": "Outlook Mail", "src": "/images/mcp-integrations/outlook-mail.jpg"},
  {"name": "PagerDuty", "src": "/images/mcp-integrations/pagerduty.svg"},
  {"name": "Productboard", "src": "/images/mcp-integrations/productboard.svg"},
  {"name": "Salesforce", "src": "/images/mcp-integrations/salesforce.svg"},
  {"name": "Sentry", "src": "/images/mcp-integrations/sentry.svg"},
  {"name": "Shopify", "src": "/images/mcp-integrations/shopify.jpg"},
  {"name": "Slack", "src": "/images/mcp-integrations/slack.svg"},
  {"name": "Square", "src": "/images/mcp-integrations/square.svg"},
  {"name": "Stripe", "src": "/images/mcp-integrations/stripe.webp"},
  {"name": "Supabase", "src": "/images/mcp-integrations/supabase.svg"},
  {"name": "Trello", "src": "/images/mcp-integrations/trello.svg"},
  {"name": "Todoist", "src": "/images/mcp-integrations/todoist.webp"},
  {"name": "Vercel", "src": "/images/mcp-integrations/vercel.svg"},
  {"name": "WhatsApp", "src": "/images/mcp-integrations/whatsapp.webp"},
  {"name": "Wrike", "src": "/images/mcp-integrations/wrike.svg"},
  {"name": "Zendesk", "src": "/images/mcp-integrations/zendesk.svg"},
  {"name": "Zoom", "src": "/images/mcp-integrations/zoom.svg"},
  {"name": "Sage", "wordmark": true},
  {"name": "Obat", "wordmark": true},
  {"name": "ProGBat", "wordmark": true},
] as const;
