/**
 * Extracts the two `<path d="…">` attributes from each card-3 tile shape SVG
 * and writes a generated TS module the visual component can import.
 *
 * The shape SVGs ship a fill path and a dashed-border path; we want both so
 * the component can drive empty vs. logo states without inlining the raw SVG.
 *
 * Run: `bun run scripts/build-tile-shapes.ts`
 */

import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";

const SHAPES = [
  "left-bottom-up",
  "left-top-down",
  "right-bottom-up",
] as const;

const IN_DIR = path.resolve(
  process.cwd(),
  "public/images/solution/card-3/logos",
);
const OUT_FILE = path.resolve(
  process.cwd(),
  "src/components/sections/solution/card-3-tile-shapes.ts",
);

interface ShapeData {
  viewBox: string;
  fillPath: string;
  borderPath: string;
}

function extract(svg: string): ShapeData {
  const viewBoxMatch = svg.match(/viewBox="([^"]+)"/);
  if (!viewBoxMatch) throw new Error("no viewBox");

  const pathRe = /<path[\s\S]*?d="([^"]+)"[\s\S]*?\/>/g;
  const paths: string[] = [];
  let m: RegExpExecArray | null;
  while ((m = pathRe.exec(svg)) !== null) paths.push(m[1]);
  if (paths.length < 2) {
    throw new Error(`expected ≥2 paths, found ${paths.length}`);
  }
  return {
    viewBox: viewBoxMatch[1],
    fillPath: paths[0],
    borderPath: paths[1],
  };
}

async function main() {
  const entries: Array<[string, ShapeData]> = [];
  for (const slug of SHAPES) {
    const svg = await readFile(path.join(IN_DIR, `${slug}.svg`), "utf8");
    entries.push([slug, extract(svg)]);
    console.log(`  ✓ ${slug}`);
  }

  const header = `// AUTO-GENERATED by scripts/build-tile-shapes.ts — do not edit by hand.
// Source SVGs live in public/images/solution/card-3/logos/*.svg.
// Re-run \`bun run scripts/build-tile-shapes.ts\` to regenerate.

export type CardThreeTileShape = ${SHAPES.map((s) => `"${s}"`).join(" | ")};

export interface CardThreeTileShapeData {
  viewBox: string;
  fillPath: string;
  borderPath: string;
}

export const CARD_THREE_TILE_SHAPES: Record<
  CardThreeTileShape,
  CardThreeTileShapeData
> = {
`;
  const body = entries
    .map(
      ([slug, data]) =>
        `  "${slug}": {\n    viewBox: ${JSON.stringify(data.viewBox)},\n    fillPath:\n      ${JSON.stringify(
          data.fillPath,
        )},\n    borderPath:\n      ${JSON.stringify(data.borderPath)},\n  },`,
    )
    .join("\n");
  const footer = `\n};\n`;

  await writeFile(OUT_FILE, header + body + footer, "utf8");
  console.log(`\nWrote ${OUT_FILE}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
